-- V1: users (no public registration; only administrators create users)
CREATE TABLE users (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    username              VARCHAR(50)  NOT NULL,
    password              VARCHAR(100) NOT NULL,
    role                  VARCHAR(20)  NOT NULL,
    enabled               BOOLEAN      NOT NULL DEFAULT TRUE,
    must_change_password  BOOLEAN      NOT NULL DEFAULT FALSE,
    failed_login_attempts INT          NOT NULL DEFAULT 0,
    locked_until          TIMESTAMP(6) NULL,
    token_not_before      TIMESTAMP(6) NULL,
    last_login_at         TIMESTAMP(6) NULL,
    created_at            TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'PHARMACIST', 'EMPLOYEE'))
);

CREATE INDEX idx_users_role ON users (role);
CREATE INDEX idx_users_last_login ON users (last_login_at);
