-- V2: drug catalog (categories + drugs). Note: no purchase price on drugs.
CREATE TABLE categories
(
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_categories_name UNIQUE (name)
);

CREATE TABLE drugs
(
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name                VARCHAR(150) NOT NULL,
    generic_name        VARCHAR(150) NULL,
    barcode             VARCHAR(50)  NULL,
    manufacturer        VARCHAR(150) NULL,
    category_id         BIGINT       NULL,
    dosage_form         VARCHAR(30)  NULL,
    strength            VARCHAR(50)  NULL,
    unit                VARCHAR(30)  NULL,
    description         VARCHAR(500) NULL,
    minimum_stock_level INT          NOT NULL DEFAULT 0,
    current_quantity    INT          NOT NULL DEFAULT 0,
    active              BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_drugs_barcode UNIQUE (barcode),
    CONSTRAINT fk_drugs_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE INDEX idx_drugs_name ON drugs (name);
CREATE INDEX idx_drugs_generic_name ON drugs (generic_name);
CREATE INDEX idx_drugs_category ON drugs (category_id);
CREATE INDEX idx_drugs_active ON drugs (active);
