-- V3: inventory batches. One row per purchase; historical prices are never overwritten.
CREATE TABLE stock_batches
(
    id                 BIGINT         GENERATED BY DEFAULT AS IDENTITY,
    drug_id            BIGINT         NOT NULL,
    quantity_received  INT            NOT NULL,
    remaining_quantity INT            NOT NULL,
    unit_purchase_price DECIMAL(19,4) NOT NULL,
    supplier           VARCHAR(150)   NULL,
    batch_number       VARCHAR(100)   NULL,
    expiration_date    DATE           NULL,
    received_at        TIMESTAMP(6)   NOT NULL,
    created_at         TIMESTAMP(6)   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_stock_batches_drug FOREIGN KEY (drug_id) REFERENCES drugs (id),
    CONSTRAINT ck_stock_batches_remaining CHECK (remaining_quantity >= 0),
    CONSTRAINT ck_stock_batches_received CHECK (quantity_received >= 0)
);

CREATE INDEX idx_stock_batches_drug_id ON stock_batches (drug_id);
CREATE INDEX idx_stock_batches_expiration ON stock_batches (expiration_date);
CREATE INDEX idx_stock_batches_drug_expiration ON stock_batches (drug_id, expiration_date);
CREATE INDEX idx_stock_batches_received_at ON stock_batches (received_at);
CREATE INDEX idx_stock_batches_supplier ON stock_batches (supplier);
