-- V7: append-only audit trail (no API allows updates or deletes)
CREATE TABLE audit_logs
(
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT       NULL,
    action      VARCHAR(40)  NOT NULL,
    entity_type VARCHAR(40)  NULL,
    entity_id   BIGINT       NULL,
    description VARCHAR(500) NULL,
    ip_address  VARCHAR(45)  NULL,
    created_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE INDEX idx_audit_logs_user_id ON audit_logs (user_id);
CREATE INDEX idx_audit_logs_action ON audit_logs (action);
CREATE INDEX idx_audit_logs_created_at ON audit_logs (created_at);
CREATE INDEX idx_audit_logs_entity ON audit_logs (entity_type, entity_id);
